import{a as M,S as q,i as a}from"./assets/vendor-03da8548.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&n(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const T="https://pixabay.com/api/";async function g(o,e,s){try{return(await M.get(T,{params:{key:"42985969-a702e02b9d921ed7e13374797",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:s,page:e}})).data}catch(n){throw console.log("Error",n),n()}}const l=document.querySelector(".gallery"),b=new q(".gallery a",{captionsData:"alt"});b.refresh();function y(o){o.forEach(e=>{const s=`<li class="img-blok">
        <a href="${e.largeImageURL}">     
    <img  src="${e.webformatURL}"
    data-source="${e.largeImageURL}"
    alt="${e.tags}">
     <ul class="image-descript">
      <li><h3>likes</h3><p>${e.likes}</p></li>
      <li><h3>views</h3><p>${e.views}</p></li>
      <li><h3>comments</h3><p>${e.comments}</p></li>
      <li><h3>downloads</h3><p>${e.downloads}</p></li>
     </ul>
   </a>
   </li>`;l.insertAdjacentHTML("beforeend",s)}),b.refresh()}function L(){const o=document.createElement("p");o.classList.add("end-message"),o.textContent="We're sorry, but you've reached the end of search results.",l.insertAdjacentElement("afterend",o)}let c="",i=1;const d=15,H=document.querySelector(".form"),w=document.querySelector(".search-input"),v=document.querySelector(".loader"),u=document.querySelector(".btn-load-more"),p=document.querySelector(".scroll-top"),h=()=>{v.style.display="flex"},E=()=>{v.style.display="none"},S=()=>{document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")};window.onload=S;H.addEventListener("submit",async o=>{if(o.preventDefault(),f(),c=w.value.trim(),i=1,l.innerHTML="",!c.length){a.error({color:"#fff021",message:"Please fill in the field for search query.",position:"topRight"}),l.innerHTML="";return}C(),h();try{const e=await g(c,i,d),s=e.totalHits;if(e.hits.length===0){l.innerHTML="",a.error({color:"#EF4040",messageColor:"#ffffff",message:"❌ Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),f();return}else y(e.hits),w.value="",$();d*i>=s&&(f(),L())}catch(e){console.log("Error fetching images:",e),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{E(),S()}u.addEventListener("click",async()=>{h();try{u&&(i+=1);const e=await g(c,i,d),s=e.totalHits;y(e.hits),h(),d*i>=s&&(f(),L());const n=l.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:n*3,behavior:"smooth"})}catch(e){console.error("Error fetching more images:",e),a.error({title:"Error",message:`Error fetching more images: ${e}`})}finally{E()}})});function $(){u.style.display="block"}function f(){u.style.display="none"}function C(){const o=document.querySelector(".end-message");o&&o.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?p.style.display="flex":p.style.display="none"});function O(){window.scrollTo({top:0,behavior:"smooth"})}p.addEventListener("click",O);
//# sourceMappingURL=commonHelpers.js.map
